

const RentCondition = () => {
    return (
        <div className="mt-10 bg-[#F8F3FF]">

            <div className="max-w-6xl mx-auto py-10 px-2 ">
            <h1 className="text-xl my-2 text-gray-700 font-opanSans">Properties for Rent in UAE</h1>
            <p className="text-gray-700 font-opanSans">UAE is a huge country with a strong economy and significant effect in the GCC region. Thinking of moving there is expected as it offers its citizens and residents a unique living atmosphere and standards whatever their age, nationality, culture, or religion. Its diverse community is what distinguishes it so having a comfortable stay there is guaranteed. In addition, people usually head to the UAE for better education for their children, a prominent career path, a good investment, or a new business venture.</p>
<p className="mt-2 text-gray-700 font-opanSans">So if you are planning to move to this country or even living here but thinking of relocating, you must be searching for a new home. In the UAE, renting a property is the most common option for many residents as it has many advantages. Leasing a property means flexibility in the residential period, location, type of unit, and the amount paid. In addition, it’s more suitable for those who don’t prefer paying all their cash to own a unit, aren’t planning for a permanent stay, or prefer to live in a new community for a change.</p>
<p className="mt-2 text-gray-700 font-opanSans">After deciding to rent in this awesome country, finding out which emirate to live in is your next step. The highly recommended and in-demand ones are Dubai, Abu Dhabi, and Sharjah for different reasons. Let’s start with the most vibrant and fascinating one, which is Dubai. This gem is surely an optimum living destination. It offers you a lavish lifestyle, high-quality services, various unit options, and most importantly promising career chances. Not just that, you will have access to astonishing attractions like Burj Khalifa, Museum of the Future, themed parks, and much more..</p>
<p className="mt-2 text-gray-700 font-opanSans">There are many properties for rent in Dubai so you will surely find one that matches your demand across its various communities. Palm Jumeirah, Dubai Marina, and Jumeirah Beach Residences are among the top living areas in the city where you can enjoy your stay. The units in Dubai also come in different sizes to fit all needs. You can lease an apartment, studio, villa, or even a penthouse in this emirate. Moreover, the area of the house is an important thing while searching for a new home. If you’re living on your own or have a small family, then a studio or apartment is more than perfect.</p>
            </div>
            
            <div className="max-w-6xl mx-auto py-5 px-2">
            <h1 className="text-xl my-2 text-gray-700 font-opanSans">Top Properties for Rent in UAE</h1>
            <p className="text-gray-700 font-opanSans">The size of the apartments for rent in Dubai starts from 57 sqm, while the studio sizes start from 30 sqm. On the other hand, for those who are dreaming of a big house with a spacious area, then the villa or penthouse options are more suitable. The area of villas for rent in Dubai starts from 153 sqm and the townhouses sizes start from 86 sqm. In addition, the penthouse areas start from 130 sqm.</p>
<p className="mt-2 text-gray-700 font-opanSans">Furthermore, the rental amounts differ according to the type of unit, community, and size, meaning that you can always find a cheap or lavish option as it all depends on your requirements. The starting leasing amount in Dubai is AED 11,111/year for apartments, AED 75,000/year for penthouses, AED 40,000/year for villas, and AED 25,000/year for townhouses.</p>
<p className="mt-2 text-gray-700 font-opanSans">The second emirate, featuring a lovely living setting, is Abu Dhabi, the capital of the UAE. It’s well known for its cozy and calm atmosphere, making it an optimum spot for those who prefer less vibrant settings. Not just that, it is a family-friendly city so if you’re coming with your family, here is your place surely. In Abu Dhabi, everything you need is supported starting from the basic needs to the leisure ones. Besides, this emirate is 1 hour and a half from Dubai so you can reach it effortlessly. Yas Island, Al Bateen, and Reem Island are among the top living areas in this city at which you can enjoy a comfortable stay. Some of them also overlook the Arabian Gulf, allowing you to relish a waterfront stay if you prefer.</p>
<p className="mt-2 text-gray-700 font-opanSans">In Abu Dhabi, you will find various properties for rent including studios, apartments, villas, and duplexes. The starting size of studios is 46 sqm, for Abu Dhabi apartments it’s 107 sqm, for villas it’s 111 sqm, for townhouses it’s 131 sqm, and for duplexes it’s 148 sqm. Moreover, the leasing amounts are also variable. The leasing amount starts at AED 14,000/year for studios, AED 24,000/year for apartments and villas, AED 37,000 for duplexes, and AED 34,000/year for townhouses.</p>
<p className="mt-2 text-gray-700 font-opanSans">Last but not least, Sharjah is undoubtedly a prominent city to have the residency you deserve. In this city, you will enjoy various services and amenities and find many awesome places to visit. In addition, it’s home to many recognizable universities so if you’re coming for education purposes or your kids are in the last school years, this emirate is ideal. It’s also known for its reasonable prices and affordable living standard compared to other emirates. Besides, you can find various career opportunities in Dubai while living in Sharjah as both are 30 minutes away from each other, meaning that you can easily commute between them.</p>
<p className="mt-2 text-gray-700 font-opanSans">In Sharjah, whatever type of property for rent you want, it’s available as the city features numerous kinds of units with ranging sizes and rental prices. In addition, there are different outstanding areas in which you can live here like Al Nahda, Al Majaz, and Al Qasimia. They offer a top living atmosphere and modern lifestyle, ensuring you a prominent stay.</p>
<p className="mt-2 text-gray-700 font-opanSans">The sizes of the apartment for lease in Sharjah start at 102 sqm, while for the studios it starts at 32 sqm. Moreover, the starting size for villas is 148 sqm and for townhouses it’s 185 sqm. If you’re wondering about the rental range for the units, here are the ranging prices for each type. The lease amount for Sharjah apartments starts at AED 10,000/year and the townhouses' rentals start from AED 60,000/year. In addition, the rental prices of villas in Sharjah start from 26,000/year. Everything you need to know about the properties for rent in the UAE is here; you will surely enjoy an amazing residency in this great country.</p>
            </div>

           

        </div>
    );
};

export default RentCondition;